name: CI_TF2

on:
  push:
    paths:
      - 'deepctr/**'
      - 'tests/**'
      - 'setup.py'
      - 'setup.cfg'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'deepctr/**'
      - 'tests/**'
      - 'setup.py'
      - 'setup.cfg'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
            tf-version: "2.10.0"
            use-legacy-keras: "0"
          - python-version: "3.10"
            tf-version: "2.15.0"
            use-legacy-keras: "0"
          - python-version: "3.11"
            tf-version: "2.15.0"
            use-legacy-keras: "0"
          - python-version: "3.10"
            tf-version: "2.20.0"
            use-legacy-keras: "1"
          - python-version: "3.11"
            tf-version: "2.20.0"
            use-legacy-keras: "1"
          - python-version: "3.12"
            tf-version: "2.20.0"
            use-legacy-keras: "1"
    env:
      TF_USE_LEGACY_KERAS: ${{ matrix.use-legacy-keras }}

    steps:
      - uses: actions/checkout@v5

      - name: Setup python environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -q --upgrade pip setuptools wheel
          python -m pip install -q tensorflow==${{ matrix.tf-version }}
          if [ "${{ matrix.use-legacy-keras }}" = "1" ]; then
            python -m pip install -q tf-keras==${{ matrix.tf-version }}
          fi
          python -m pip install -q pytest pytest-cov
          python -m pip install -e .
          python -m pip check

      - name: Test with pytest
        timeout-minutes: 180
        run: |
          pytest --cov=deepctr --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: pytest
          name: py${{ matrix.python-version }}-tf${{ matrix.tf-version }}
