name: CI_TF1

on:
  push:
    paths:
      - 'deepctr/**'
      - 'tests/**'
      - 'setup.py'
      - 'setup.cfg'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'deepctr/**'
      - 'tests/**'
      - 'setup.py'
      - 'setup.cfg'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      matrix:
        include:
          - python-version: "3.6"
            tf-version: "1.15.0"
    steps:

      - uses: actions/checkout@v4

      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip3 install -q tensorflow==${{ matrix.tf-version }}
          pip install -q protobuf==3.19.0
          pip install -q requests
          pip install -q pytest pytest-cov python-coveralls
          pip install -e .
      - name: Test with pytest
        timeout-minutes: 360
        run: |
          pytest --cov=deepctr --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.xml
          flags: pytest
          name: py${{ matrix.python-version }}-tf${{ matrix.tf-version }}
